version: "3.3"
services:
  stream-safer:
    container_name: stream-safer
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ".:/stream-safer"
    restart: "on-failure:5"
    ports:
      - "8080:80"
